### ISSUE TITLE
Is this project active. I'm not able to run it locally

### ISSUE THREAD

**Issue by openwork** [slabiak/AppointmentScheduler#34]
There are issues with the adding availability and breaks.

**Comment by peterboivin** [comment]
It is definitely broken.  I forked the project and I have fixed some of it but not all of it.

**Comment by slabiak** [comment]
I’ll take a look at it in the next few days :)

**Comment by openwork** [comment]
Thanks .. Just to mention the problem is creating the availability for provider and adding breaks too : 
2023-03-14 05:56:39.725  WARN 10304 --- [io-8080-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 2 errors
Field error in object 'breakModel' on field 'end': rejected value [07:00]; codes [typeMismatch.breakModel.end,typeMismatch.end,typeMismatch.java.time.LocalTime,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [breakModel.end,end]; arguments []; default message [end]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.time.LocalTime' for property 'end'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.time.LocalTime] for value '07:00'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [07:00]]
Field error in object 'breakModel' on field 'start': rejected value [07:00]; codes [typeMismatch.breakModel.start,typeMismatch.start,typeMismatch.java.time.LocalTime,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [breakModel.start,start]; arguments []; default message [start]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.time.LocalTime' for property 'start'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.time.LocalTime] for value '07:00'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [07:00]]]

**Comment by peterboivin** [comment]
Here is my fork.  I might help you.  https://github.com/peterboivin/AppointmentScheduler

**Comment by slabiak** [comment]
I found the issue and will publish fixed version today/tomorrow. I will also deploy it online cause current demo is not working anymore.

**Comment by openwork** [comment]
Thanks @slabiak

**Comment by openwork** [comment]
> Here is my fork. I might help you. https://github.com/peterboivin/AppointmentScheduler

Thanks @peterboivin, I tried your fork too, but there was issue related to Calendar.js too.. I didn't look much into it, but Calendar was not rendering.

**Comment by openwork** [comment]
Hello @slabiak  Thanks for the immediate actions and fixing it.. Let me try this and will update you.
